add: notchIcons
deus-app/deus-creatio pull request #43
Opened 2023-12-29 04:56 UTC by s1f102100793

### 行ったこと
https://github.com/deus-app/deus-creatio/issues/40
このissueで求められていたアイコンを4つ追加した。

![スクリーンショット 2023-12-29 134520](https://github.com/deus-app/deus-creatio/assets/85666759/ab945e03-1d52-4ee5-85d5-3c229250825a)

2023-12-29 05:14 UTC, solufa requested changes
ブラウザのリサイズには対応している？
スマホ対応までは不要だけど横幅1200~1980pxくらいの変動には追従して欲しい

1200と1980両方のスクショを貼って欲しい

2023-12-29 05:14 UTC, solufa commented on client/src/components/icons/ClockIcon.tsx
> +      return () => clearInterval(intervalId);
ここの処理複雑に見える

それにsetTimeoutは返り値を取らない

2023-12-29 05:14 UTC, solufa commented on client/src/components/icons/ClockIcon.tsx
> +  const [currentTime, setCurrentTime] = useState(new Date());
あっちこっちでnew Dateしているのも読み手に辛い

2023-12-29 06:06 UTC, s1f102100793 commented
左側の時刻は12pxでdeus-app.comの文字と同じ大きさにして、右側の3つのアイコンはリロードのアイコンのようにsizeで大きさを指定するようにしました。

720px
![スクリーンショット 2023-12-29 144913](https://github.com/deus-app/deus-creatio/assets/85666759/39d3ecb2-bfa9-4d85-bab1-7ee1887ecc2a)
1080px　自分のモニターが全画面表示で1080pxなので全画面表示のスクリーンショットになります。
![image](https://github.com/deus-app/deus-creatio/assets/85666759/f55da666-fcd6-4cb2-b225-cfda3f51671c)

2023-12-29 06:15 UTC, s1f102100793 commented on client/src/components/icons/ClockIcon.tsx
> +      return () => clearInterval(intervalId);
パフォーマンスを上げようと無駄なレンダリングを防ぐコードを書き、複雑なコードになってしまったので、
もっとシンプルに、1秒ごとにuseEffectで現在時刻を更新し続けるコードに変えます。

2023-12-29 06:24 UTC, solufa commented
720pxのときのアイコン位置がずれててめっちゃダサい・・・

2023-12-29 06:29 UTC, solufa commented on client/src/components/icons/ClockIcon.tsx
> +      return () => clearInterval(intervalId);
自分が無能なだけなのに存在しない問題を勝手に産み出して言い訳に使うな
それにこの程度の描画更新パフォーマンスを問題にするならReact使うべきではないレベルの話になってくる

パフォーマンス問題ってのはだいたい秒間数万オーダーの操作をするようになって体感するもの

2023-12-29 09:53 UTC, s1f102100793 commented
ClockIconコンポーネントの修正と、ノッチアイコンのサイズと位置の修正をしました。

720px
![image](https://github.com/deus-app/deus-creatio/assets/85666759/c4ffecff-50c7-4471-95fb-221061c72872)
1080px
![image](https://github.com/deus-app/deus-creatio/assets/85666759/cfe8c7a7-b87d-41d9-963a-0ab0d2db8b35)

2023-12-29 10:50 UTC, solufa requested changes
アイコンのコンテナ要素は割とサイズ変動なのにアイコン自体はサイズ固定している？
ここは目立つのでやるなら相応の実装をして欲しい

2023-12-29 10:50 UTC, solufa commented on client/src/components/icons/ClockIcon.tsx
> +export const ClockIcon = () => {
このコンポーネント、Iconじゃないな・・・
SVGに変換するか時刻文字列を返すカスタムHookにしたら良いのでは

2023-12-29 10:50 UTC, solufa commented on client/src/pages/@components/InfoArea/infoArea.module.css
> +  text-align: center;
z-index使っているのが気になる
100という値が何か他の数字との大小関係に依存していることを読み取りにくい
justify-content使っているのにtext-alignも重ねているのも怪しい

2023-12-29 13:00 UTC, s1f102100793 commented on client/src/components/icons/ClockIcon.tsx
> +export const ClockIcon = () => {
カスタムHookに追加します。
/@hooksに追加で良いですか？それとも/src/hooksフォルダを作成してそこに追加すれば良いですかね？
@の有り無しについて自分の中で言語化できていないので、確認してもいいですか？

2023-12-29 13:28 UTC, s1f102100793 commented
ノッチの真ん中の黒い部分がサイズ変動になっているので、アイコン自体もサイズ変動するようにします。
この場合propsでsizeを指定しなくなるので、他の～Iconとpropsの引数の形が変わって～Iconというコンポーネントに
sizeを指定するという統一性が無くなるのですが、それでも大丈夫ですか？
その部分だけすこし気になっています。

2023-12-29 14:00 UTC, solufa commented on client/src/components/icons/ClockIcon.tsx
> +export const ClockIcon = () => {
@はpageコンポーネントを含まない程度の意味しかない

2023-12-29 14:02 UTC, solufa commented
統一性がないなら新たなコンポーネントグループを作るとかすれば良かろう

2023-12-29 17:22 UTC, solufa requested changes
> 高さが何pxでもこのバランスで表示をします。

とあるが、別の作業をしていてローカルで試せないのでバランスを維持している方法を解説して欲しい
時刻の文字サイズをvh、余白やコンテナ幅を%で変動させていることまでは読み取れたけどアイコンのサイズはどうやってバランスを維持している？

2023-12-29 17:22 UTC, solufa commented on client/src/pages/@hooks/useCurrentTime.tsx
> +    formattedTimeElm: <span>{formatTime(currentTime)}</span>,
Spanで囲うだけならHooksで返す合理性がない

2023-12-29 17:22 UTC, solufa commented on client/src/components/icons/ClockIcon.tsx
> +};
これがどこで使われているのかわからん

2023-12-30 00:16 UTC, s1f102100793 commented on client/src/components/icons/ClockIcon.tsx
> +};
すみません。消し忘れです。

2023-12-30 00:28 UTC, s1f102100793 commented
・前回のコミットで「高さが何pxでもこのバランスで表示をします。」と言っていたのですが、先ほどもう一度確認すると
リロードをするとアイコンが表示されなく、その後画面サイズが変わるとアイコンが表示されるようになり、表示し続ける状況だと気づき、松田さんの指摘の通りだったのでsvgのwidthを33%で固定にし、アイコンサイズのバランスを取るようにしました。

・useCurrentTimeではcurrentTimeを返すようにして、hh:mm形式の時刻を表示するTimeDisplayHHMMを作成し、そのコンポーネントにcurrentTimeを入れることでノッチの時刻表示を行うように変更しました。

お手数をおかけしてすみません。

2023-12-30 03:59 UTC, solufa requested changes
視野が狭くて低レベルなミスが多い

2023-12-30 03:59 UTC, solufa commented on client/src/pages/@hooks/useCurrentTime.tsx
> +  };
拡張子がtsxなのはなぜ

2023-12-30 03:59 UTC, solufa commented on client/src/components/Notch/TimeDisplayHHMM .tsx
> +};
ファイル名色々おかしい気がする

2023-12-30 03:59 UTC, solufa commented on client/src/components/Notch/TimeDisplayHHMM .tsx
> +};
テキストを返すだけの関数をTSXとして使うセンスの無さどうかしてる

2023-12-30 03:59 UTC, solufa commented on client/src/components/Notch/WifiIcon.tsx
> +        })`}
ズームして中央取り直すだけならviewBox調整すりゃいいのでは

2023-12-30 16:19 UTC, s1f102100793 commented
完全に自分の注意力の低さが原因です。
もっと一つ一つの選択に考えを持ちながらコードを書きます。

2024-01-01 06:46 UTC, s1f102100793 commented
1つ前のレビューでコメントがあった部分を修正しました。

2024-01-01 06:56 UTC, s1f102100793 commented
レビューリクエストしたのですが、まだ最新をfetchしてrebaseしてないので少し待って欲しいです。

2024-01-01 06:59 UTC, solufa requested changes
初回コミットよりだいぶ読みやすくなった

2024-01-01 06:59 UTC, solufa commented on client/src/components/Notch/ClockIcon.tsx
> +};
これIconじゃないな

DigitalClockコンポーネントとして@componentsに配置しuseCurrentTimeを分離せずここに置いた方が責務が閉じていて読みやすい
他でもcurrentTimeを使う場面が出たら分離すればよい

2024-01-01 08:52 UTC, s1f102100793 commented
少し待ってください。
cssがないので@componentsにファイルを直接置きます

2024-01-01 09:10 UTC, s1f102100793 commented
DigitalClockコンポーネントを追加しました。

2024-01-01 09:21 UTC, solufa approved these changes
LGTM
年末年始も作業しているのは素晴らしい

レビュー前後でこのPRの質がどれだけ変わったか見返しておくと良い
deus-templateの方にもコメントしたのでコンフリクトしていない内に早く修正したほうが楽だと思う

2024-01-01 09:21 UTC, merged