Feature/login
deus-app/deus-creatio pull request #48
Opened 2024-01-07 13:37 UTC by s1f102100793

### 行ったこと
https://github.com/deus-app/deus-creatio/issues/47のissueを行いました。
ログインしていない状態で画像の右上のLoginの部分の作成と、左上の「アプリ新規生成」ボタンの非表示を行いました。

![スクリーンショット 2024-01-07 221637](https://github.com/deus-app/deus-creatio/assets/85666759/ad37055e-ed86-4ca3-b1af-4ab2cfdbdb1f)

ChatAreaとInfoAreaの部分はログイン状態による条件ではなく
アプリを作成したユーザーかどうかによって変更要望などを入力する事ができるのかなと思ったので変更を行っていないです。

2024-01-07 13:50 UTC, solufa requested changes
スクショを見る限り、Loginボタン周りに線が密集していてダサい

2024-01-07 14:25 UTC, s1f102100793 commented
![image](https://github.com/deus-app/deus-creatio/assets/85666759/a9b6a140-4105-46b7-8d01-86c6cbbdc121)

こんな感じで、ログインしている時の表示と同じように、基本的にはアイコンと文字を表示して
カーソルを当てたときにだけ、白のborderを表示するようにすればいいですか？

2024-01-07 14:38 UTC, solufa commented
現行と同じデザインにはなるが、ホバー時に線が密集する問題を引き継いでしまう

2024-01-08 11:42 UTC, s1f102100793 commented
![image](https://github.com/deus-app/deus-creatio/assets/85666759/716ec7b2-c11f-4638-8b3a-a63864f9e83a)

こんな感じでホバー時に、背景の色を変えるのはどうですか？

2024-01-08 15:18 UTC, solufa commented
それでよい

2024-01-09 06:55 UTC, s1f102100793 commented
修正しました。

2024-01-09 11:03 UTC, solufa approved these changes
LGTM

2024-01-09 11:03 UTC, merged